In [3]:
%%capture 
import gym
import numpy as np
import matplotlib.pyplot as plt
import sys 
import os
from collections import deque
# !git clone https://github.com/clementbernardd/code_ml_rl
# !pip install fire
# sys.path.insert(0, os.path.join('code_ml_rl', 'poly_ai_maze', 'poly_ai_maze', 'envs') )
# sys.path.insert(0, 'code_ml_rl' )
from code_ml_rl.evaluation import EvalRL
from code_ml_rl.poly_ai_maze.poly_ai_maze.envs.maze import PolyAIMaze
env = PolyAIMaze()

In [4]:
# Reset the environment and initialize the maze
state = env.reset()
print(state)
# Plot a visual representation of the maze
env.render()


[[0 2 0 0 0 2 0 0 0 0]
 [0 2 0 2 0 2 0 0 2 0]
 [0 2 0 2 0 2 0 0 2 0]
 [0 0 0 2 0 0 0 0 2 0]
 [0 2 0 2 2 3 2 2 2 0]
 [0 2 2 2 0 0 0 0 0 0]
 [0 0 0 2 0 2 2 2 3 2]
 [0 2 0 2 0 0 0 0 0 4]
 [0 2 0 2 2 2 2 2 2 3]
 [1 2 0 0 0 0 0 0 0 0]]
🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦
🟦👣⬜👣👣👣⬜👣👣👣👣🟦
🟦👣⬜👣⬜👣⬜👣👣⬜👣🟦
🟦👣⬜👣⬜👣⬜👣👣⬜👣🟦
🟦👣👣👣⬜👣👣👣👣⬜👣🟦
🟦👣⬜👣⬜⬜💣⬜⬜⬜👣🟦
🟦👣⬜⬜⬜👣👣👣👣👣👣🟦
🟦👣👣👣⬜👣⬜⬜⬜💣⬜🟦
🟦👣⬜👣⬜👣👣👣👣👣🏠🟦
🟦👣⬜👣⬜⬜⬜⬜⬜⬜💣🟦
🟦⛹⬜👣👣👣👣👣👣👣👣🟦
🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦


In [15]:
# Reset the environment
state = env.reset()
# Try to go up 
new_state = env.step(1)
# Vizualize the result
env.render()

🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦
🟦👣⬜👣👣👣⬜👣👣👣👣🟦
🟦👣⬜👣⬜👣⬜👣👣⬜👣🟦
🟦👣⬜👣⬜👣⬜👣👣⬜👣🟦
🟦👣👣👣⬜👣👣👣👣⬜👣🟦
🟦👣⬜👣⬜⬜💣⬜⬜⬜👣🟦
🟦👣⬜⬜⬜👣👣👣👣👣👣🟦
🟦👣👣👣⬜👣⬜⬜⬜💣⬜🟦
🟦👣⬜👣⬜👣👣👣👣👣🏠🟦
🟦⛹⬜👣⬜⬜⬜⬜⬜⬜💣🟦
🟦👣⬜👣👣👣👣👣👣👣👣🟦
🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦
       (UP)



In [22]:
# Start from the beginning
env.reset()
# Try to do random action 201 times
for i in range(201) : 
    # Command to do random actions
    action = np.random.randint(0,4)
    # Do the action in the environment
    new_state, reward, done, _ = env.step(action)
    print(f'{i+1}: reward : {reward},done : {done}')
env.render()

1: reward : -1,done : False
2: reward : -1,done : False
3: reward : -1,done : False
4: reward : -1,done : False
5: reward : -1,done : False
6: reward : -1,done : False
7: reward : -1,done : False
8: reward : -1,done : False
9: reward : -1,done : False
10: reward : -1,done : False
11: reward : -1,done : False
12: reward : -1,done : False
13: reward : -1,done : False
14: reward : -1,done : False
15: reward : -1,done : False
16: reward : -1,done : False
17: reward : -1,done : False
18: reward : -1,done : False
19: reward : -1,done : False
20: reward : -1,done : False
21: reward : -1,done : False
22: reward : -1,done : False
23: reward : -1,done : False
24: reward : -1,done : False
25: reward : -1,done : False
26: reward : -1,done : False
27: reward : -1,done : False
28: reward : -1,done : False
29: reward : -1,done : False
30: reward : -1,done : False
31: reward : -1,done : False
32: reward : -1,done : False
33: reward : -1,done : False
34: reward : -1,done : False
35: reward : -1,done : 

In [45]:
# 使用Q-learning算法去迭代
def get_state(state):
    for i in range(10):
        for j in range(10):
            if state[i, j] == 1:
                return 10 * i + j


class SolutionFormat:
    """The code that is asked to fill"""
    def __init__(self):
        """Any initialisation that you want. 
           If you use an algorithm that uses a Q-table (as advised), you can initialize your Q-table here
           You can set any hyperparameter here.
        """
        self.q_table = None 
        self.epsilon = 0.9
        self.gamma = 0.99
        self.lr = 0.01

    def action(self, state):
        """Return an action to do."""
        state = get_state(state)
        # 采用\epsilon-greedy策略
        if np.random.random() > self.epsilon or sum(self.q_table[state]) == 0:
            idx = np.random.randint(4)
        else:
            idx = np.argmax(self.q_table[state])
        return idx
    
    def update(self, state, action ,new_state, reward, done, info, episode):
        """Update the policy."""
        state = get_state(state)
        q = self.q_table[get_state(new_state)]
        q_target = self.q_table[state,action]
        if done:
            q_predict = reward
        else:
            q_predict = reward + self.gamma * np.max(q)
        
        self.q_table[state, action] += self.lr * (q_predict - q_target)

    def reset(self) : 
        """Reset your algorithm to be adapted to other maze. 
           For instance, it could be to reset to 0 the values of the Q-tables
        """
        np.random.seed(2024)
        self.q_table = np.zeros((100,4))

In [46]:
# test_code
solution = SolutionFormat()
solution.reset()
n_episodes = 100
for e in range(n_episodes):
    state = env.reset()
    rewards = 0
    done = False
    while not done:
        action = solution.action(state)
        new_state, reward, done, info = env.step(action)
        solution.update(state, action, new_state, reward, done, info, e)
        state = new_state
        rewards += reward

************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************


In [47]:
solution = SolutionFormat()
solution.reset()
env.reset()
evaluation = EvalRL(env=env,  solution=solution)
score = evaluation.eval()
print(f'Score: {score}')


************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
************************* Game over *************************
********